### ISSUE TITLE
Doesnt seem to be working on VS4M

### ISSUE THREAD

**Issue by b099l3** [colbylwilliams/DefaultDesigner#2]
I updated Visual Studio for Mac to 7.4 Preview (7.4 build 839)

Installed version 1.2 of the Default Designer but the order of the 

And the order is 
![image](https://user-images.githubusercontent.com/877327/34872379-8a3b91bc-f788-11e7-8ba2-61a8e9e9df9a.png)

Not too sure what has happened but Im going to try to see if I can find whats wrong.

*Update*
 I updated MonoDevelop.Addins to 0.4.1 then recreated the project and ran the make file but still no luck. I have a [fork](https://github.com/b099l3/DefaultDesigner) if that helps with this code

**Comment by b099l3** [comment]
Ah I looked at what you did the last time VS4M updated [here](https://github.com/colbylwilliams/DefaultDesigner/commit/27a304db52f32009a2f484d95313a3c7e7033474)

And have updated the MonoDevelop.Addins package and im going to run 
`mono /Applications/Visual\ Studio.app/Contents/Resources/lib/monodevelop/bin/vstool.exe setup pack DefaultDesigner.dll` and see if that works

**Comment by daniil-shumko** [comment]
Also, does not work on Visual Studio for Mac 7.3.3 (build 5)

**Comment by colbylwilliams** [comment]
@b099l3 @daniil-shumko give [v1.3](https://github.com/colbylwilliams/DefaultDesigner/releases/tag/v1.3) a shot and let me know if it fixes the issue.

**Comment by daniil-shumko** [comment]
![image](https://user-images.githubusercontent.com/7705571/34955424-3232c8f0-fa1c-11e7-82b1-54cb641ad78b.png)
This is the error I get
@colbylwilliams 
_Updated:_
It works fine when I double click the .xib files on my VS4M!

**Comment by colbylwilliams** [comment]
ah, I built it against current preview... lemme build against stable

**Comment by b099l3** [comment]
Ah nice job man thanks! Works on my version 7.4 Preview (7.4 build 839)

How did you know it was this:

```
<Extension
  path="/MonoDevelop/Ide/DisplayBindings">
    <DisplayBinding
      class="MonoDevelop.MacDev.XcodeInterfaceBuilderDisplayBinding"
      id="InterfaceBuilderBeforeIOSDesinger"
      insertbefore="iOSDesigner" />
</Extension>
```

Is there Docs to know it was iOSDesigner?

**Comment by colbylwilliams** [comment]
@daniil-shumko I updated the package in the releases to one that's built against stable (7.3.x) so you shouldn't get the error anymore

**Comment by colbylwilliams** [comment]
@b099l3 no docs, just a buddy on the VS4M team.  Thanks for reporting the issue.

**Comment by b099l3** [comment]
Ah no worries, Thanks again for fixing it!

**Comment by daniil-shumko** [comment]
@colbylwilliams thanks for the fix
